In [27]:
import tensorflow as tf

## Membuat tensor 5,5 random

In [28]:
random_tensor = tf.Variable(tf.random.normal([5,5], mean=4, stddev=1, dtype=tf.float32))
random_tensor.read_value().numpy()

array([[1.6739347, 4.665907 , 3.2272513, 3.6794307, 3.6094396],
       [3.7301965, 4.2274327, 4.812372 , 3.5158038, 3.5684786],
       [4.392893 , 5.172362 , 6.6454377, 1.9424376, 3.5952003],
       [5.369534 , 5.990097 , 4.3525515, 5.540507 , 5.561638 ],
       [3.6593363, 3.573243 , 4.4167976, 2.9131768, 3.322129 ]],
      dtype=float32)

# Membuat List

In [29]:
list = [[77,31,67,88,33],[55,27,11,5,6],[78,77,43,41,52],[99,82,3,5,95],[13,45,77,72,52]]
prime_tensor = tf.convert_to_tensor(list, dtype=tf.int64).numpy()

In [30]:
print("Tampilan dimensi dari random tensor")
print(random_tensor.read_value().numpy())

print("Tampilan dimensi dari prime tensor")
print(prime_tensor)

Tampilan dimensi dari random tensor
[[1.6739347 4.665907  3.2272513 3.6794307 3.6094396]
 [3.7301965 4.2274327 4.812372  3.5158038 3.5684786]
 [4.392893  5.172362  6.6454377 1.9424376 3.5952003]
 [5.369534  5.990097  4.3525515 5.540507  5.561638 ]
 [3.6593363 3.573243  4.4167976 2.9131768 3.322129 ]]
Tampilan dimensi dari prime tensor
[[77 31 67 88 33]
 [55 27 11  5  6]
 [78 77 43 41 52]
 [99 82  3  5 95]
 [13 45 77 72 52]]


In [31]:
#Penjumlahan
tf.add(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 78.673935 ,  35.66591  ,  70.22725  ,  91.67943  ,  36.60944  ],
       [ 58.730198 ,  31.227432 ,  15.812372 ,   8.515804 ,   9.568479 ],
       [ 82.39289  ,  82.17236  ,  49.64544  ,  42.942436 ,  55.5952   ],
       [104.36954  ,  87.9901   ,   7.3525515,  10.540506 , 100.56164  ],
       [ 16.659336 ,  48.573242 ,  81.416794 ,  74.91318  ,  55.32213  ]],
      dtype=float32)>

In [32]:
# Pengurangan
tf.subtract(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-75.326065  , -26.334093  , -63.772747  , -84.32057   ,
        -29.39056   ],
       [-51.269802  , -22.772568  ,  -6.187628  ,  -1.4841962 ,
         -2.4315214 ],
       [-73.60711   , -71.82764   , -36.35456   , -39.057564  ,
        -48.4048    ],
       [-93.63046   , -76.0099    ,   1.3525515 ,   0.54050684,
        -89.43836   ],
       [ -9.340664  , -41.426758  , -72.583206  , -69.08682   ,
        -48.67787   ]], dtype=float32)>

In [33]:
# Perkalian
tf.multiply(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[128.89297 , 144.64311 , 216.22583 , 323.78992 , 119.1115  ],
       [205.16081 , 114.140686,  52.936096,  17.57902 ,  21.410872],
       [342.64563 , 398.27185 , 285.7538  ,  79.639946, 186.95041 ],
       [531.58386 , 491.18796 ,  13.057654,  27.702534, 528.3556  ],
       [ 47.571373, 160.79593 , 340.0934  , 209.74873 , 172.7507  ]],
      dtype=float32)>

In [34]:
# Pembagian
tf.divide(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.02173941, 0.15051313, 0.04816793, 0.04181171, 0.10937696],
       [0.06782176, 0.15657158, 0.43748838, 0.70316076, 0.5947464 ],
       [0.05631914, 0.06717353, 0.15454507, 0.04737653, 0.06913847],
       [0.05423772, 0.07304996, 1.4508505 , 1.1081014 , 0.05854356],
       [0.2814874 , 0.0794054 , 0.05736101, 0.04046079, 0.0638871 ]],
      dtype=float32)>

In [35]:
# Logaritma
tf.math.log(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.51517695, 1.5402822 , 1.1716309 , 1.3027581 , 1.2835525 ],
       [1.3164608 , 1.4415948 , 1.5711901 , 1.2572682 , 1.2721393 ],
       [1.479988  , 1.6433294 , 1.8939306 , 0.6639437 , 1.2795997 ],
       [1.6807412 , 1.7901076 , 1.4707623 , 1.712086  , 1.7158927 ],
       [1.2972817 , 1.2734735 , 1.4854149 , 1.0692441 , 1.2006059 ]],
      dtype=float32)>

In [36]:
#Perpangkatan
tf.pow(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1.6899171e+17, 5.4578068e+20, 1.2353683e+34,           inf,
        2.4860664e+18],
       [2.7876865e+31, 8.0180923e+16, 3.2059098e+07, 5.3718414e+02,
        2.0648979e+03],
       [          inf,           inf, 2.3362238e+35, 6.6409556e+11,
        7.8995208e+28],
       [          inf,           inf, 8.2457802e+01, 5.2209253e+03,
                  inf],
       [2.1097464e+07, 7.7235024e+24,           inf, 2.7190199e+33,
        1.2991452e+27]], dtype=float32)>

In [37]:
tf.matmul(random_tensor,prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1048.4298 ,  890.50793,  591.2156 ,  581.22986,  788.2891 ],
       [1289.5538 , 1049.2069 ,  788.67725,  821.2112 ,  918.2667 ],
       [1380.1156 , 1108.5961 ,  919.63135,  953.46594,  893.04443],
       [1703.22   , 1367.9299 , 1057.6772 , 1109.0645 , 1255.0211 ],
       [1154.3995 ,  938.38666,  738.94696,  774.73566,  821.37354]],
      dtype=float32)>

In [38]:
tf.argmax(random_tensor, axis=0).numpy()

array([3, 3, 2, 3, 3], dtype=int64)

In [39]:
tf.argmin(random_tensor, axis=0).numpy()

array([0, 4, 0, 2, 4], dtype=int64)

In [40]:
print(f"Size Awal : {random_tensor.shape} {prime_tensor.shape}" )

Size Awal : (5, 5) (5, 5)


In [41]:
concat_tensor_1 = tf.concat([random_tensor, prime_tensor], axis=0)
concat_tensor_2 = tf.concat([random_tensor, prime_tensor], axis=1)
print(f"Size yang sudah di concat (axis = 0) : {concat_tensor_1.shape}")
print(f"Size yang sudah di concat (axis = 1) : {concat_tensor_2.shape}")

Size yang sudah di concat (axis = 0) : (10, 5)
Size yang sudah di concat (axis = 1) : (5, 10)


In [42]:
# random_tensor secara descending
tf.sort(random_tensor, direction="DESCENDING").numpy()

array([[4.665907 , 3.6794307, 3.6094396, 3.2272513, 1.6739347],
       [4.812372 , 4.2274327, 3.7301965, 3.5684786, 3.5158038],
       [6.6454377, 5.172362 , 4.392893 , 3.5952003, 1.9424376],
       [5.990097 , 5.561638 , 5.540507 , 5.369534 , 4.3525515],
       [4.4167976, 3.6593363, 3.573243 , 3.322129 , 2.9131768]],
      dtype=float32)

In [43]:
# random_tensor secara ascending
tf.sort(random_tensor, direction="ASCENDING").numpy()

array([[1.6739347, 3.2272513, 3.6094396, 3.6794307, 4.665907 ],
       [3.5158038, 3.5684786, 3.7301965, 4.2274327, 4.812372 ],
       [1.9424376, 3.5952003, 4.392893 , 5.172362 , 6.6454377],
       [4.3525515, 5.369534 , 5.540507 , 5.561638 , 5.990097 ],
       [2.9131768, 3.322129 , 3.573243 , 3.6593363, 4.4167976]],
      dtype=float32)

In [44]:
# prime_tensor secara descending
tf.sort(prime_tensor, direction="DESCENDING").numpy()

array([[88, 77, 67, 33, 31],
       [55, 27, 11,  6,  5],
       [78, 77, 52, 43, 41],
       [99, 95, 82,  5,  3],
       [77, 72, 52, 45, 13]], dtype=int64)

In [45]:
# prime_tensor secara ascending
tf.sort(prime_tensor, direction="ASCENDING").numpy()

array([[31, 33, 67, 77, 88],
       [ 5,  6, 11, 27, 55],
       [41, 43, 52, 77, 78],
       [ 3,  5, 82, 95, 99],
       [13, 45, 52, 72, 77]], dtype=int64)